// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_5fbase_2eproto;
class ClientHead;
class ClientHeadDefaultTypeInternal;
extern ClientHeadDefaultTypeInternal _ClientHead_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientHead* Arena::CreateMaybeMessage<::ClientHead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum CSMessageId : int {
  ss_msgid_invalid = 0,
  ss_msgid_heartbeat = 1,
  ss_msgid_user_login = 2,
  CSMessageId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CSMessageId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CSMessageId_IsValid(int value);
constexpr CSMessageId CSMessageId_MIN = ss_msgid_invalid;
constexpr CSMessageId CSMessageId_MAX = ss_msgid_user_login;
constexpr int CSMessageId_ARRAYSIZE = CSMessageId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CSMessageId_descriptor();
template<typename T>
inline const std::string& CSMessageId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CSMessageId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CSMessageId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CSMessageId_descriptor(), enum_t_value);
}
inline bool CSMessageId_Parse(
    const std::string& name, CSMessageId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CSMessageId>(
    CSMessageId_descriptor(), name, value);
}
// ===================================================================

class ClientHead PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientHead) */ {
 public:
  inline ClientHead() : ClientHead(nullptr) {};
  virtual ~ClientHead();

  ClientHead(const ClientHead& from);
  ClientHead(ClientHead&& from) noexcept
    : ClientHead() {
    *this = ::std::move(from);
  }

  inline ClientHead& operator=(const ClientHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientHead& operator=(ClientHead&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClientHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientHead* internal_default_instance() {
    return reinterpret_cast<const ClientHead*>(
               &_ClientHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientHead& a, ClientHead& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientHead* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientHead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientHead* New() const final {
    return CreateMaybeMessage<ClientHead>(nullptr);
  }

  ClientHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientHead& from);
  void MergeFrom(const ClientHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientHead";
  }
  protected:
  explicit ClientHead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_client_5fbase_2eproto);
    return ::descriptor_table_client_5fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqTimeFieldNumber = 2,
    kSyncIdFieldNumber = 1,
  };
  // int64 req_time = 2;
  void clear_req_time();
  ::PROTOBUF_NAMESPACE_ID::int64 req_time() const;
  void set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_req_time() const;
  void _internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 sync_id = 1;
  void clear_sync_id();
  ::PROTOBUF_NAMESPACE_ID::int32 sync_id() const;
  void set_sync_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sync_id() const;
  void _internal_set_sync_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ClientHead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 req_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 sync_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientHead

// int32 sync_id = 1;
inline void ClientHead::clear_sync_id() {
  sync_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientHead::_internal_sync_id() const {
  return sync_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ClientHead::sync_id() const {
  // @@protoc_insertion_point(field_get:ClientHead.sync_id)
  return _internal_sync_id();
}
inline void ClientHead::_internal_set_sync_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sync_id_ = value;
}
inline void ClientHead::set_sync_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sync_id(value);
  // @@protoc_insertion_point(field_set:ClientHead.sync_id)
}

// int64 req_time = 2;
inline void ClientHead::clear_req_time() {
  req_time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClientHead::_internal_req_time() const {
  return req_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClientHead::req_time() const {
  // @@protoc_insertion_point(field_get:ClientHead.req_time)
  return _internal_req_time();
}
inline void ClientHead::_internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  req_time_ = value;
}
inline void ClientHead::set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_req_time(value);
  // @@protoc_insertion_point(field_set:ClientHead.req_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::CSMessageId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CSMessageId>() {
  return ::CSMessageId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fbase_2eproto
