// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_server_5fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_server_5fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "server_base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_server_5fcommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_server_5fcommon_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_5fcommon_2eproto;
class SSHeartbeat;
class SSHeartbeatDefaultTypeInternal;
extern SSHeartbeatDefaultTypeInternal _SSHeartbeat_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SSHeartbeat* Arena::CreateMaybeMessage<::SSHeartbeat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum SSHeartbeat_SSMessageId : int {
  SSHeartbeat_SSMessageId_ss_msgid_invalid = 0,
  SSHeartbeat_SSMessageId_ss_msgid = 1073741824,
  SSHeartbeat_SSMessageId_SSHeartbeat_SSMessageId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SSHeartbeat_SSMessageId_SSHeartbeat_SSMessageId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SSHeartbeat_SSMessageId_IsValid(int value);
constexpr SSHeartbeat_SSMessageId SSHeartbeat_SSMessageId_SSMessageId_MIN = SSHeartbeat_SSMessageId_ss_msgid_invalid;
constexpr SSHeartbeat_SSMessageId SSHeartbeat_SSMessageId_SSMessageId_MAX = SSHeartbeat_SSMessageId_ss_msgid;
constexpr int SSHeartbeat_SSMessageId_SSMessageId_ARRAYSIZE = SSHeartbeat_SSMessageId_SSMessageId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SSHeartbeat_SSMessageId_descriptor();
template<typename T>
inline const std::string& SSHeartbeat_SSMessageId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SSHeartbeat_SSMessageId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SSHeartbeat_SSMessageId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SSHeartbeat_SSMessageId_descriptor(), enum_t_value);
}
inline bool SSHeartbeat_SSMessageId_Parse(
    const std::string& name, SSHeartbeat_SSMessageId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SSHeartbeat_SSMessageId>(
    SSHeartbeat_SSMessageId_descriptor(), name, value);
}
// ===================================================================

class SSHeartbeat PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SSHeartbeat) */ {
 public:
  inline SSHeartbeat() : SSHeartbeat(nullptr) {};
  virtual ~SSHeartbeat();

  SSHeartbeat(const SSHeartbeat& from);
  SSHeartbeat(SSHeartbeat&& from) noexcept
    : SSHeartbeat() {
    *this = ::std::move(from);
  }

  inline SSHeartbeat& operator=(const SSHeartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSHeartbeat& operator=(SSHeartbeat&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SSHeartbeat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SSHeartbeat* internal_default_instance() {
    return reinterpret_cast<const SSHeartbeat*>(
               &_SSHeartbeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SSHeartbeat& a, SSHeartbeat& b) {
    a.Swap(&b);
  }
  inline void Swap(SSHeartbeat* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSHeartbeat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SSHeartbeat* New() const final {
    return CreateMaybeMessage<SSHeartbeat>(nullptr);
  }

  SSHeartbeat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SSHeartbeat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SSHeartbeat& from);
  void MergeFrom(const SSHeartbeat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSHeartbeat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SSHeartbeat";
  }
  protected:
  explicit SSHeartbeat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_server_5fcommon_2eproto);
    return ::descriptor_table_server_5fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef SSHeartbeat_SSMessageId SSMessageId;
  static constexpr SSMessageId ss_msgid_invalid =
    SSHeartbeat_SSMessageId_ss_msgid_invalid;
  static constexpr SSMessageId ss_msgid =
    SSHeartbeat_SSMessageId_ss_msgid;
  static inline bool SSMessageId_IsValid(int value) {
    return SSHeartbeat_SSMessageId_IsValid(value);
  }
  static constexpr SSMessageId SSMessageId_MIN =
    SSHeartbeat_SSMessageId_SSMessageId_MIN;
  static constexpr SSMessageId SSMessageId_MAX =
    SSHeartbeat_SSMessageId_SSMessageId_MAX;
  static constexpr int SSMessageId_ARRAYSIZE =
    SSHeartbeat_SSMessageId_SSMessageId_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  SSMessageId_descriptor() {
    return SSHeartbeat_SSMessageId_descriptor();
  }
  template<typename T>
  static inline const std::string& SSMessageId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, SSMessageId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function SSMessageId_Name.");
    return SSHeartbeat_SSMessageId_Name(enum_t_value);
  }
  static inline bool SSMessageId_Parse(const std::string& name,
      SSMessageId* value) {
    return SSHeartbeat_SSMessageId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTransIdFieldNumber = 2,
    kReqTimeFieldNumber = 3,
    kMsgIdFieldNumber = 1,
  };
  // string trans_id = 2;
  void clear_trans_id();
  const std::string& trans_id() const;
  void set_trans_id(const std::string& value);
  void set_trans_id(std::string&& value);
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  std::string* mutable_trans_id();
  std::string* release_trans_id();
  void set_allocated_trans_id(std::string* trans_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_trans_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_trans_id(
      std::string* trans_id);
  private:
  const std::string& _internal_trans_id() const;
  void _internal_set_trans_id(const std::string& value);
  std::string* _internal_mutable_trans_id();
  public:

  // int64 req_time = 3;
  void clear_req_time();
  ::PROTOBUF_NAMESPACE_ID::int64 req_time() const;
  void set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_req_time() const;
  void _internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 msg_id = 1;
  void clear_msg_id();
  ::PROTOBUF_NAMESPACE_ID::int32 msg_id() const;
  void set_msg_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_msg_id() const;
  void _internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SSHeartbeat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trans_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 req_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 msg_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fcommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSHeartbeat

// int32 msg_id = 1;
inline void SSHeartbeat::clear_msg_id() {
  msg_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SSHeartbeat::_internal_msg_id() const {
  return msg_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SSHeartbeat::msg_id() const {
  // @@protoc_insertion_point(field_get:SSHeartbeat.msg_id)
  return _internal_msg_id();
}
inline void SSHeartbeat::_internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  msg_id_ = value;
}
inline void SSHeartbeat::set_msg_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:SSHeartbeat.msg_id)
}

// string trans_id = 2;
inline void SSHeartbeat::clear_trans_id() {
  trans_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SSHeartbeat::trans_id() const {
  // @@protoc_insertion_point(field_get:SSHeartbeat.trans_id)
  return _internal_trans_id();
}
inline void SSHeartbeat::set_trans_id(const std::string& value) {
  _internal_set_trans_id(value);
  // @@protoc_insertion_point(field_set:SSHeartbeat.trans_id)
}
inline std::string* SSHeartbeat::mutable_trans_id() {
  // @@protoc_insertion_point(field_mutable:SSHeartbeat.trans_id)
  return _internal_mutable_trans_id();
}
inline const std::string& SSHeartbeat::_internal_trans_id() const {
  return trans_id_.Get();
}
inline void SSHeartbeat::_internal_set_trans_id(const std::string& value) {
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SSHeartbeat::set_trans_id(std::string&& value) {
  
  trans_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SSHeartbeat.trans_id)
}
inline void SSHeartbeat::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:SSHeartbeat.trans_id)
}
inline void SSHeartbeat::set_trans_id(const char* value,
    size_t size) {
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SSHeartbeat.trans_id)
}
inline std::string* SSHeartbeat::_internal_mutable_trans_id() {
  
  return trans_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SSHeartbeat::release_trans_id() {
  // @@protoc_insertion_point(field_release:SSHeartbeat.trans_id)
  return trans_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SSHeartbeat::set_allocated_trans_id(std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trans_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SSHeartbeat.trans_id)
}
inline std::string* SSHeartbeat::unsafe_arena_release_trans_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SSHeartbeat.trans_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return trans_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SSHeartbeat::unsafe_arena_set_allocated_trans_id(
    std::string* trans_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      trans_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSHeartbeat.trans_id)
}

// int64 req_time = 3;
inline void SSHeartbeat::clear_req_time() {
  req_time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 SSHeartbeat::_internal_req_time() const {
  return req_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 SSHeartbeat::req_time() const {
  // @@protoc_insertion_point(field_get:SSHeartbeat.req_time)
  return _internal_req_time();
}
inline void SSHeartbeat::_internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  req_time_ = value;
}
inline void SSHeartbeat::set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_req_time(value);
  // @@protoc_insertion_point(field_set:SSHeartbeat.req_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SSHeartbeat_SSMessageId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SSHeartbeat_SSMessageId>() {
  return ::SSHeartbeat_SSMessageId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_server_5fcommon_2eproto
