// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_server_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_server_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_server_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_server_5fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_5fbase_2eproto;
class ServerHead;
class ServerHeadDefaultTypeInternal;
extern ServerHeadDefaultTypeInternal _ServerHead_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ServerHead* Arena::CreateMaybeMessage<::ServerHead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum SSMessageId : int {
  ss_msgid_invalid = 0,
  ss_msgid_heartbeat = 1073741824,
  SSMessageId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SSMessageId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SSMessageId_IsValid(int value);
constexpr SSMessageId SSMessageId_MIN = ss_msgid_invalid;
constexpr SSMessageId SSMessageId_MAX = ss_msgid_heartbeat;
constexpr int SSMessageId_ARRAYSIZE = SSMessageId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SSMessageId_descriptor();
template<typename T>
inline const std::string& SSMessageId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SSMessageId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SSMessageId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SSMessageId_descriptor(), enum_t_value);
}
inline bool SSMessageId_Parse(
    const std::string& name, SSMessageId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SSMessageId>(
    SSMessageId_descriptor(), name, value);
}
// ===================================================================

class ServerHead PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerHead) */ {
 public:
  inline ServerHead() : ServerHead(nullptr) {};
  virtual ~ServerHead();

  ServerHead(const ServerHead& from);
  ServerHead(ServerHead&& from) noexcept
    : ServerHead() {
    *this = ::std::move(from);
  }

  inline ServerHead& operator=(const ServerHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerHead& operator=(ServerHead&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerHead* internal_default_instance() {
    return reinterpret_cast<const ServerHead*>(
               &_ServerHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerHead& a, ServerHead& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerHead* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerHead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerHead* New() const final {
    return CreateMaybeMessage<ServerHead>(nullptr);
  }

  ServerHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerHead& from);
  void MergeFrom(const ServerHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerHead";
  }
  protected:
  explicit ServerHead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_server_5fbase_2eproto);
    return ::descriptor_table_server_5fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransIdFieldNumber = 1,
    kReqTimeFieldNumber = 2,
    kFromServerFieldNumber = 3,
    kDestServerFieldNumber = 4,
    kUserIdFieldNumber = 5,
  };
  // string trans_id = 1;
  void clear_trans_id();
  const std::string& trans_id() const;
  void set_trans_id(const std::string& value);
  void set_trans_id(std::string&& value);
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  std::string* mutable_trans_id();
  std::string* release_trans_id();
  void set_allocated_trans_id(std::string* trans_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_trans_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_trans_id(
      std::string* trans_id);
  private:
  const std::string& _internal_trans_id() const;
  void _internal_set_trans_id(const std::string& value);
  std::string* _internal_mutable_trans_id();
  public:

  // int64 req_time = 2;
  void clear_req_time();
  ::PROTOBUF_NAMESPACE_ID::int64 req_time() const;
  void set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_req_time() const;
  void _internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 from_server = 3;
  void clear_from_server();
  ::PROTOBUF_NAMESPACE_ID::int64 from_server() const;
  void set_from_server(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_from_server() const;
  void _internal_set_from_server(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 dest_server = 4;
  void clear_dest_server();
  ::PROTOBUF_NAMESPACE_ID::int64 dest_server() const;
  void set_dest_server(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_dest_server() const;
  void _internal_set_dest_server(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 user_id = 5;
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::int64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:ServerHead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trans_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 req_time_;
  ::PROTOBUF_NAMESPACE_ID::int64 from_server_;
  ::PROTOBUF_NAMESPACE_ID::int64 dest_server_;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerHead

// string trans_id = 1;
inline void ServerHead::clear_trans_id() {
  trans_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ServerHead::trans_id() const {
  // @@protoc_insertion_point(field_get:ServerHead.trans_id)
  return _internal_trans_id();
}
inline void ServerHead::set_trans_id(const std::string& value) {
  _internal_set_trans_id(value);
  // @@protoc_insertion_point(field_set:ServerHead.trans_id)
}
inline std::string* ServerHead::mutable_trans_id() {
  // @@protoc_insertion_point(field_mutable:ServerHead.trans_id)
  return _internal_mutable_trans_id();
}
inline const std::string& ServerHead::_internal_trans_id() const {
  return trans_id_.Get();
}
inline void ServerHead::_internal_set_trans_id(const std::string& value) {
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ServerHead::set_trans_id(std::string&& value) {
  
  trans_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ServerHead.trans_id)
}
inline void ServerHead::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ServerHead.trans_id)
}
inline void ServerHead::set_trans_id(const char* value,
    size_t size) {
  
  trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ServerHead.trans_id)
}
inline std::string* ServerHead::_internal_mutable_trans_id() {
  
  return trans_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ServerHead::release_trans_id() {
  // @@protoc_insertion_point(field_release:ServerHead.trans_id)
  return trans_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServerHead::set_allocated_trans_id(std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trans_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ServerHead.trans_id)
}
inline std::string* ServerHead::unsafe_arena_release_trans_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ServerHead.trans_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return trans_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ServerHead::unsafe_arena_set_allocated_trans_id(
    std::string* trans_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      trans_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ServerHead.trans_id)
}

// int64 req_time = 2;
inline void ServerHead::clear_req_time() {
  req_time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::_internal_req_time() const {
  return req_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::req_time() const {
  // @@protoc_insertion_point(field_get:ServerHead.req_time)
  return _internal_req_time();
}
inline void ServerHead::_internal_set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  req_time_ = value;
}
inline void ServerHead::set_req_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_req_time(value);
  // @@protoc_insertion_point(field_set:ServerHead.req_time)
}

// int64 from_server = 3;
inline void ServerHead::clear_from_server() {
  from_server_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::_internal_from_server() const {
  return from_server_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::from_server() const {
  // @@protoc_insertion_point(field_get:ServerHead.from_server)
  return _internal_from_server();
}
inline void ServerHead::_internal_set_from_server(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  from_server_ = value;
}
inline void ServerHead::set_from_server(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_from_server(value);
  // @@protoc_insertion_point(field_set:ServerHead.from_server)
}

// int64 dest_server = 4;
inline void ServerHead::clear_dest_server() {
  dest_server_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::_internal_dest_server() const {
  return dest_server_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::dest_server() const {
  // @@protoc_insertion_point(field_get:ServerHead.dest_server)
  return _internal_dest_server();
}
inline void ServerHead::_internal_set_dest_server(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  dest_server_ = value;
}
inline void ServerHead::set_dest_server(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_dest_server(value);
  // @@protoc_insertion_point(field_set:ServerHead.dest_server)
}

// int64 user_id = 5;
inline void ServerHead::clear_user_id() {
  user_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ServerHead::user_id() const {
  // @@protoc_insertion_point(field_get:ServerHead.user_id)
  return _internal_user_id();
}
inline void ServerHead::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  user_id_ = value;
}
inline void ServerHead::set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:ServerHead.user_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SSMessageId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SSMessageId>() {
  return ::SSMessageId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_server_5fbase_2eproto
