// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_common.proto

#include "server_common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class SSHeartbeatDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SSHeartbeat> _instance;
} _SSHeartbeat_default_instance_;
static void InitDefaultsscc_info_SSHeartbeat_server_5fcommon_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_SSHeartbeat_default_instance_;
    new (ptr) ::SSHeartbeat();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SSHeartbeat::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SSHeartbeat_server_5fcommon_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SSHeartbeat_server_5fcommon_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_server_5fcommon_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_server_5fcommon_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_server_5fcommon_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_server_5fcommon_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SSHeartbeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SSHeartbeat, msg_id_),
  PROTOBUF_FIELD_OFFSET(::SSHeartbeat, trans_id_),
  PROTOBUF_FIELD_OFFSET(::SSHeartbeat, req_time_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::SSHeartbeat)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_SSHeartbeat_default_instance_),
};

const char descriptor_table_protodef_server_5fcommon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023server_common.proto\032\021server_base.proto"
  "\"x\n\013SSHeartbeat\022\016\n\006msg_id\030\001 \001(\005\022\020\n\010trans"
  "_id\030\002 \001(\t\022\020\n\010req_time\030\003 \001(\003\"5\n\013SSMessage"
  "Id\022\024\n\020ss_msgid_invalid\020\000\022\020\n\010ss_msgid\020\200\200\200"
  "\200\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_server_5fcommon_2eproto_deps[1] = {
  &::descriptor_table_server_5fbase_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_server_5fcommon_2eproto_sccs[1] = {
  &scc_info_SSHeartbeat_server_5fcommon_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_server_5fcommon_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_5fcommon_2eproto = {
  false, false, descriptor_table_protodef_server_5fcommon_2eproto, "server_common.proto", 170,
  &descriptor_table_server_5fcommon_2eproto_once, descriptor_table_server_5fcommon_2eproto_sccs, descriptor_table_server_5fcommon_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_server_5fcommon_2eproto::offsets,
  file_level_metadata_server_5fcommon_2eproto, 1, file_level_enum_descriptors_server_5fcommon_2eproto, file_level_service_descriptors_server_5fcommon_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_server_5fcommon_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_server_5fcommon_2eproto)), true);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SSHeartbeat_SSMessageId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_server_5fcommon_2eproto);
  return file_level_enum_descriptors_server_5fcommon_2eproto[0];
}
bool SSHeartbeat_SSMessageId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1073741824:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr SSHeartbeat_SSMessageId SSHeartbeat::ss_msgid_invalid;
constexpr SSHeartbeat_SSMessageId SSHeartbeat::ss_msgid;
constexpr SSHeartbeat_SSMessageId SSHeartbeat::SSMessageId_MIN;
constexpr SSHeartbeat_SSMessageId SSHeartbeat::SSMessageId_MAX;
constexpr int SSHeartbeat::SSMessageId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void SSHeartbeat::InitAsDefaultInstance() {
}
class SSHeartbeat::_Internal {
 public:
};

SSHeartbeat::SSHeartbeat(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SSHeartbeat)
}
SSHeartbeat::SSHeartbeat(const SSHeartbeat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_trans_id().empty()) {
    trans_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_trans_id(),
      GetArena());
  }
  ::memcpy(&req_time_, &from.req_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&msg_id_) -
    reinterpret_cast<char*>(&req_time_)) + sizeof(msg_id_));
  // @@protoc_insertion_point(copy_constructor:SSHeartbeat)
}

void SSHeartbeat::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SSHeartbeat_server_5fcommon_2eproto.base);
  trans_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&req_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&msg_id_) -
      reinterpret_cast<char*>(&req_time_)) + sizeof(msg_id_));
}

SSHeartbeat::~SSHeartbeat() {
  // @@protoc_insertion_point(destructor:SSHeartbeat)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SSHeartbeat::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  trans_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SSHeartbeat::ArenaDtor(void* object) {
  SSHeartbeat* _this = reinterpret_cast< SSHeartbeat* >(object);
  (void)_this;
}
void SSHeartbeat::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SSHeartbeat::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SSHeartbeat& SSHeartbeat::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SSHeartbeat_server_5fcommon_2eproto.base);
  return *internal_default_instance();
}


void SSHeartbeat::Clear() {
// @@protoc_insertion_point(message_clear_start:SSHeartbeat)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trans_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&req_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&msg_id_) -
      reinterpret_cast<char*>(&req_time_)) + sizeof(msg_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SSHeartbeat::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string trans_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_trans_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "SSHeartbeat.trans_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 req_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          req_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SSHeartbeat::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SSHeartbeat)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 msg_id = 1;
  if (this->msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_msg_id(), target);
  }

  // string trans_id = 2;
  if (this->trans_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trans_id().data(), static_cast<int>(this->_internal_trans_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SSHeartbeat.trans_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_trans_id(), target);
  }

  // int64 req_time = 3;
  if (this->req_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_req_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SSHeartbeat)
  return target;
}

size_t SSHeartbeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SSHeartbeat)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trans_id = 2;
  if (this->trans_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trans_id());
  }

  // int64 req_time = 3;
  if (this->req_time() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_req_time());
  }

  // int32 msg_id = 1;
  if (this->msg_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_msg_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SSHeartbeat::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SSHeartbeat)
  GOOGLE_DCHECK_NE(&from, this);
  const SSHeartbeat* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SSHeartbeat>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SSHeartbeat)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SSHeartbeat)
    MergeFrom(*source);
  }
}

void SSHeartbeat::MergeFrom(const SSHeartbeat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SSHeartbeat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.trans_id().size() > 0) {
    _internal_set_trans_id(from._internal_trans_id());
  }
  if (from.req_time() != 0) {
    _internal_set_req_time(from._internal_req_time());
  }
  if (from.msg_id() != 0) {
    _internal_set_msg_id(from._internal_msg_id());
  }
}

void SSHeartbeat::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SSHeartbeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSHeartbeat::CopyFrom(const SSHeartbeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SSHeartbeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSHeartbeat::IsInitialized() const {
  return true;
}

void SSHeartbeat::InternalSwap(SSHeartbeat* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  trans_id_.Swap(&other->trans_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SSHeartbeat, msg_id_)
      + sizeof(SSHeartbeat::msg_id_)
      - PROTOBUF_FIELD_OFFSET(SSHeartbeat, req_time_)>(
          reinterpret_cast<char*>(&req_time_),
          reinterpret_cast<char*>(&other->req_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SSHeartbeat::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SSHeartbeat* Arena::CreateMaybeMessage< ::SSHeartbeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SSHeartbeat >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
